COMMENT = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
WHITESPACE = _{(" " | "\t")+}
ident = @{ XID_START ~ XID_CONTINUE* }
string = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\""}
named_parameter = ${ident ~ "=" ~ string ~ ""}
verb = ${ "@" ~ ident ~ ("(" ~ named_parameter ~ ("," ~ named_parameter)* ~ ")")?}
scope = { "{" ~ statements ~ "}" }
statement = {verb* ~ scope?}
statement_terminator = _{";" | NEWLINE}
statements = { statement ~ (statement_terminator ~ statement)* }
ask = _{SOI ~ statements ~ EOI }