name: Build and Publish askld image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'docker/askld/**'
      - 'askld/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'Makefile'
      - '.github/workflows/askld-docker.yml'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      RAW_IMAGE_NAME: ${{ github.repository_owner }}/askld
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure image name
        run: echo "IMAGE_NAME=${RAW_IMAGE_NAME,,}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=semver,pattern=v{{version}}

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/askld/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
